# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdateGroup():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def test_update_group(self):
    self.open_home_page()
    self.login()
    self.update_group()
    self.logout()

  def open_home_page(self):
    self.driver.get("http://localhost/addressbook/")

  def login(self):
    self.driver.find_element(By.NAME, "pass").send_keys("secret")
    self.driver.find_element(By.NAME, "user").click()
    self.driver.find_element(By.NAME, "user").send_keys("admin")
    self.driver.find_element(By.ID, "LoginForm").click()
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def update_group(self):
    # open groups page
    self.driver.find_element(By.LINK_TEXT, "groups").click()
    # select group and update
    self.driver.find_element(By.CSS_SELECTOR, ".group:nth-child(12) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(16)").click()
    self.driver.find_element(By.NAME, "group_name").click()
    self.driver.find_element(By.NAME, "group_name").send_keys("group1")
    self.driver.find_element(By.NAME, "group_header").click()
    self.driver.find_element(By.NAME, "group_header").send_keys("group header1")
    self.driver.find_element(By.NAME, "group_footer").click()
    self.driver.find_element(By.NAME, "group_footer").send_keys("group footer1")
    self.driver.find_element(By.NAME, "update").click()

  def logout(self):
    self.driver.find_element(By.LINK_TEXT, "Logout").click()

  def teardown_method(self, method):
    self.driver.quit()